
#### register
POST http://localhost:3000/register
content-type: application/json

{
    "username": "jotajota",
    "password": "putoelque",
    "email": "gordo@teton.com",
    "anonimato": true
}


#### login 
POST http://localhost:3000/login
content-type: application/json

{
    "email": "gordo@teton.com",
    "password": "putoelque"
}

